- Developer:
    - GitHub:
        - icon: github
          href: https://github.com

- Resources:
    - Home Assistant Docs:
        - icon: home-assistant
          href: https://www.home-assistant.io/docs/
