tap "adoptopenjdk/openjdk"
tap "aws/tap"
tap "dart-lang/dart"
tap "dopplerhq/cli"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "jakehilborn/jakehilborn"
tap "koekeishiya/formulae"
tap "nikitabobko/tap"
tap "pkgxdev/made"
tap "pulumi/tap"

brew "act"
brew "libtiff"
brew "little-cms2"
brew "webp"
brew "jpeg-xl"
brew "aom"
brew "apr-util"
brew "automake"
brew "bento4"
brew "bison"
brew "boost"
brew "freetype"
brew "cairo"
brew "pycparser"
brew "cffi"
brew "chruby"
brew "libidn2"
brew "unbound"
brew "gnutls"
brew "qemu"
brew "lima"
brew "colima"
brew "libssh2"
brew "rtmpdump"
brew "freetds"
brew "gd"
brew "libzip"
brew "php"
brew "composer"
brew "libyaml"
brew "copier"
brew "csvlens"
brew "direnv"
brew "folly"
brew "fizz"
brew "wangle"
brew "fbthrift"
brew "fb303"
brew "edencommon"
brew "eslint"
brew "eza"
brew "fastfetch"
brew "fish"
brew "gcc"
brew "findutils"
brew "fzf"
brew "gdbm"
brew "gh"
brew "git"
brew "gnupg"
brew "guile"
brew "gum"
brew "jq"
brew "just"
brew "keyring"
brew "lazydocker"
brew "lazygit"
brew "libffi"
brew "mas"
brew "neovim"
brew "nvm"
brew "ollama", restart_service: true
brew "openssl@1.1"
brew "parallel"
brew "pnpm"
brew "poetry"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python@3.10"
brew "python@3.11"
brew "qsv"
brew "ruby-install"
brew "smug"
brew "starship"
brew "stow"
brew "tmux"
brew "virtualenv"
brew "watchman"
brew "wget"
brew "woff2"
brew "yt-dlp"
brew "zoxide"
brew "aws/tap/copilot-cli"
brew "dart-lang/dart/dart"
brew "dopplerhq/cli/doppler", link: false
brew "hashicorp/tap/terraform"
brew "jakehilborn/jakehilborn/displayplacer"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "pkgxdev/made/pkgx"
brew "pulumi/tap/esc"
brew "pulumi/tap/pulumi"

cask "alacritty"
cask "dbeaver-community"
cask "tableplus"
cask "font-0xproto-nerd-font"
cask "git-credential-manager"
cask "github"
cask "jan"
cask "linearmouse"
cask "ngrok"
cask "iina"
cask "raycast"
cask "arc"
cask "slack"
cask "spaceman"
cask "jordanbaird-ice"
cask "betterdisplay"

mas "Be Focused", id: 973134470
mas "Amphetamine", id: 937984704
mas "Boop", id: 1518425043
mas "ColorSlurp", id: 1287239339
mas "Couverture", id: 1552415914
mas "Hidden Bar", id: 1452453066
mas "Klack", id: 6446206067
mas "LilyView", id: 529490330
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Spark", id: 1176895641
mas "Speedtest", id: 1153157709
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
