# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

os:
  editPreset: "nvim"
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
